import Notification from "@/components/atoms/Notification";
import "../globals.scss";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Notification />
        {children}
      </body>
    </html>
  );
}
