import TodoHeader from "@/components/organisms/TodoHeader";
import "./globals.scss";
import { Montserrat } from "next/font/google";
import Menu from "@/components/organisms/Menu";
import Notification from "@/components/atoms/Notification";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "DAT DEP TRAI",
  description: "Generated by DAT DEP TRAI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Notification />
        <div className="grid grid-cols-4 grid-rows-6 bg-white w-screen h-screen">
          {/* Menu on the left */}
          <div className=" col-span-1 row-span-6 col-start-1 row-start-1">
            <Menu />
          </div>
          {/* Header on top of main */}
          <div className=" col-span-3 row-span-1 col-start-2 row-start-1 px-4">
            <TodoHeader />
          </div>
          {/* Main content (pages) */}
          <div className=" col-span-3 row-span-5 col-start-2 row-start-2 px-4">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
